### ISSUE TITLE
PHP error when assigning objects

### ISSUE THREAD

**Issue by gamma** [cosmocode/qc#1]
I'm using the qc plugin an face a problem (which seams only to occur in firefox somehow)

it reads: "qc data gatherer: started <br /> <b>Fatal error</b>: Cannot use assign-op operators with overloaded objects nor string offsets in <b>/var/www/public_html/lib/plugins/qc/renderer.php</b> on line <b>283</b><br />"

Hier ist noch mein setup:

anon_id c900272205b3f61d3336ca76e2e82055
version Git 2010-05-18
popversion  2008-02-20
language    de
now 1274192410
conf_useacl 1
conf_authtype   plain
conf_template   editing
page_count  518
page_size   1694605
page_biggest    37698
page_smallest   14
page_avg    3271.43822394
page_oldest 1233905299
media_count 594
media_size  44795717
media_biggest   13713463
media_smallest  10
media_avg   75413.6649832
cache_count 3639
cache_size  34949577
cache_biggest   722899
cache_smallest  0
cache_avg   9604.17065128
index_count 80
index_size  1086352
index_biggest   470446
index_smallest  6
index_avg   13579.4
meta_count  1887
meta_size   1888209
meta_biggest    17239
meta_smallest   1
meta_avg    1000.64069952
attic_count 7879
attic_size  15132715
attic_biggest   12341
attic_smallest  27
attic_avg   1920.63904049
attic_oldest    1238146328
user_count  11
edits_per_day   8.05247477977
plugin  config
plugin  meta
plugin  fancysearch
plugin  text
plugin  include
plugin  pagemove
plugin  popupviewer
plugin  databaseconnector
plugin  formular
plugin  externallink
plugin  tag
plugin  pagetemplater
plugin  moretoolbarbuttons
plugin  clearfloat
plugin  inetconfigproperties
plugin  siteexport
plugin  newpage
plugin  usermanager
plugin  alphaindex
plugin  sync
plugin  offlinetranslation
plugin  nbsp
plugin  javadoc
plugin  searchindex
plugin  comment
plugin  info
plugin  popularity
plugin  dir
plugin  frootysearch
plugin  pageredirect
plugin  plainmail
plugin  npd
plugin  plugin
plugin  pagelist
plugin  colorpicker
plugin  translator
plugin  odt
plugin  underconstruction
plugin  box
plugin  toc
plugin  batchedit
plugin  keywords
plugin  lang
plugin  metaheaders
plugin  reflect
plugin  translation
plugin  cacherevisionserase
plugin  googleanalytics
plugin  acl
plugin  revert
plugin  nodetailsxhtml
plugin  uparrow
pcre_version    7.4 2007-09-21
pcre_backtrack  20971520
pcre_recursion  100000
os  Linux
webserver   lighttpd/1.4.19
php_version 5.2.4-2ubuntu5.10
php_sapi    cgi-fcgi
php_memory  134217728
php_exectime    480
php_extension   zip
php_extension   xmlwriter
php_extension   libxml
php_extension   xml
php_extension   wddx
php_extension   tokenizer
php_extension   sysvshm
php_extension   sysvsem
php_extension   sysvmsg
php_extension   session
php_extension   SimpleXML
php_extension   sockets
php_extension   soap
php_extension   SPL
php_extension   shmop
php_extension   standard
php_extension   Reflection
php_extension   posix
php_extension   mime_magic
php_extension   mbstring
php_extension   json
php_extension   iconv
php_extension   hash
php_extension   gettext
php_extension   ftp
php_extension   filter
php_extension   exif
php_extension   dom
php_extension   dba
php_extension   date
php_extension   ctype
php_extension   calendar
php_extension   bz2
php_extension   bcmath
php_extension   zlib
php_extension   pcre
php_extension   openssl
php_extension   xmlreader
php_extension   cgi-fcgi
php_extension   mcrypt
php_extension   curl
php_extension   ffmpeg
php_extension   gd
php_extension   mysql
php_extension   mysqli
php_extension   PDO
php_extension   pdo_mysql
php_extension   pdo_pgsql
php_extension   pgsql
php_extension   xmlrpc

**Comment by splitbrain** [comment]
is this still happening? there were a couple of updates in the last years and it's running without any problems on multiple setups I maintain.

**Comment by gamma** [comment]
We're not using it any more.
