### ISSUE TITLE
Edit counting does not seem to work

### ISSUE THREAD

**Issue by stvoigt** [cosmocode/qc#31]
I can never get a green smiley, because I always get the message, that there is only one single author (and even only one single edit!). Even if the page was edited several times from different authors. 
You can see this on my starting page: http://www.green-logistics.iff.fraunhofer.de/biologic/start, if you take a look into the revisions, you can see, that there are a lot of different authors and edits: http://www.green-logistics.iff.fraunhofer.de/biologic/start?do=revisions
I am using the latest Hrun on different wiki setups and get the same error in every wiki.

**Comment by Parad0xMS** [comment]
I can confirm that behavior :(
I had to disable that check in the configs and would like to enable it again.

**Comment by Parad0xMS** [comment]
I can confirm that behavior :(
I had to disable that check in the configs and would like to enable it again.

**Comment by Parad0xMS** [comment]
I can confirm that behavior :(
I had to disable that check in the configs and would like to enable it again.

**Comment by Parad0xMS** [comment]
Ignore my last comment. With the updateed Version of https://github.com/cosmocode/qc/blob/master/renderer.php the Problem is fixed.
