### ISSUE TITLE
Will break with DokuWiki Index refactoring

### ISSUE THREAD

**Issue by micgro42** [cosmocode/qc#41]
The upcoming refactoring of DokuWiki's index handling in splitbrain/dokuwiki#2943 will break this plugin.

That being said, what breaks this plugin is requiring `inc/fulltext.php` directly. This isn't the right way to do things for some time now and refactoring it to use autoloading might allow this plugin to work both with the current stable version of DokuWiki and the upcoming master.

https://github.com/cosmocode/qc/blob/f392d45e2311d77f98070f35bc9b4cb38c866034/renderer.php#L5-L6

**Comment by StarArmy** [comment]
I saw the location of the renderer changed too, I saw. I made a pull request that updates that ( https://github.com/cosmocode/qc/pull/42 ) however the fulltext issue will need to be fixed still before this plugin can work again.

**Comment by StarArmy** [comment]
The plug is still broken. How do we add autoloading?
